name: Docker build and push to azure storage

on:
  push:
    branches:
      - 'master'

jobs:
  production-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PRD }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Deploy contracts and build darkforest
        run: ./scripts/ci_build_deploy.sh
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DEFAULT_RPC: ${{ secrets.DEFAULT_RPC }}
          DEPLOYER_MNEMONIC: "${{ secrets.DEPLOYER_MNEMONIC }}"
          HARDHAT_NETWORK: ${{ secrets.HARDHAT_NETWORK }}

      - name: Push to storage account
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --overwrite --account-name prddarkforestaltresearch --auth-mode key -d '$web' -s "client/dist"
      
      - name: logout
        run: |
          az logout
        if: always()

